site_name: CSC Rulebook
site_url: https://rulebook.csconfederation.com
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default 

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css
nav:
    - Introduction: introduction.md
    - League Info: league-info.md
    - CSC Conduct Guidelines: csc-conduct-guidelines.md
    - League Processes: league-processes.md
    - Transactions: transactions.md
    - Gameplay Rules: gameplay-rules.md
    - Season Overview: season-overview.md
    - Rules Committee Policies: rc-policies.md
    - Appendix: appendix.md
